### PR TITLE
Don't warn about pure-python murmur on PyPy.

### PR DESCRIPTION
**Pull request by Julian**
On PyPy, it's preferred.

### CODE REVIEW

**Comment by rthille** [comment]
Heh, apparently @davidkbainbridge didn't know we were going round-and-round with legal about submissions :-)
@Julian, we've got a new contributors agreement for submissions going forward. I've got a PR to bring the public (this) repo up to parity with our internal repo which has it.  Take a look and see if it's acceptable.

**Comment by rthille** [comment]
https://github.com/ciena/afkak/blob/b1d89302f37c2f8be83ee38ac8c55f1dad5b2506/CONTRIBUTING.md

**Comment by Julian** [comment]
I was wondering how this PR managed to sneak through that :).

I'll have a look.

**Comment by Julian** [comment]
(This is just curiosity mostly) -- were you advised that you need to use `--signoff` for every single commit rather than just asking contributors for a blanket agreement to the contributor agreement?

**Comment by rthille** [comment]
Not sure, I was on vacation for that week when it was finally worked out.  @twm ?

**Comment by rthille** [comment]
I imagine if you would prefer to just have a blanket agreement, that'd be fine too.

**Comment by Julian** [comment]
It'd be a bit easier to not need to remember before committing yeah.

**Comment by twm** [comment]
The key motivation for the `Signed-off-by` line is that it can be enforced automatically.  For example, [this pull request](https://github.com/habitat-sh/habitat/pull/1407) is failing pre-merge checks because it lacks signoffs. We don't have this automation yet, but I'd like to add it.

**Comment by Julian** [comment]
I have to ask internally, but I think we do that same automation, just by checking the list of registered committers who've submitted the ahead-of-time agreement (anyways yeah, I was mostly just curious, so if it's not worth the time, I'm OK as-is certainly, I just might need to be reminded either by a human or the automation to add the line :P).

**Pull request merged**
