### PR TITLE
lookupAddress returns the chain including CNAMEs if there are any.

### PR DESCRIPTION
**Pull request by Julian**
Hey!

Should be a simple fix here for this, lemme know what you think.

I can't run the tests locally seemingly because of some custom packages. Hope there's something here that runs them?

### CODE REVIEW

**Comment by rthille** [comment]
Hi Julian,
Thanks for the PR!  I see there's a bunch of borked stuff (flake8 failing) in this public version.  I'll see about making sure anyone can build it as soon as I can.  In the mean time, you should just be able to pull the TeamCity related stuff out to test.

**Comment by twm** [comment]
@rthille We should set up Travis here.

**Comment by Julian** [comment]
Hi guys. Just getting back to this as we're not actually using afkak yet (because of this and a couple of other things I've got on my plate) -- it's also stuff like index URLs being set to a private index. I'll give it a second or two to try to rip some of that out so that I can check if I can run things locally.

**Comment by Julian** [comment]
Yeah looks like with those two things removed they run. Cool.

**Comment by Julian** [comment]
OK, I think that should fix things now, sorry for the sloppiness here.

**Comment by Julian** [comment]
Polite ping :)

**Comment by twm** [comment]
@Julian I _think_ that this was fixed in https://github.com/ciena/afkak/releases/tag/2.4.0, since I recall having similar issues internally.

However, if address resolution is still not working for you, or you want to enhance it in any way, would you update the PR so that it merges cleanly? We also need signed-off-by lines in each commit to indicate acceptance of the DCO, as detailed in the [contribution guide](https://github.com/ciena/afkak/blob/master/CONTRIBUTING.md) We managed to get that through Legal a bit after you submitted this PR, so you may not have seen it before.

Thanks for your interest in Afkak! I'm sorry for not being more responsive here.

**Pull request closed without merging**
