### PR TITLE
Add new error codes through 31

### PR DESCRIPTION
**Pull request by twm**
Add exception types for all of the currently-defined error codes. 

* https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes
* http://kafka.apache.org/protocol.html#protocol_error_codes

This adds the codes through 31 necessary to merge the coordinated consumer implementation. I will follow up with another PR containing the rest of the defined codes.

### CODE REVIEW

**Comment by twm** [comment]
Marking this [WIP] as they have added even more error codes since I last looked.

**Comment by rthille** [comment]
Looks like something is still trying to import check_error

**Comment by rthille** [comment]
Looks like the tests failed due to Kafka being 💩

**Comment by twm** [comment]
Yeah, I am pretty close to disabling the flaky tests out of sheer frustrating. I have hope that when I add Kafka 1.01 to the suite it will reveal a different pattern.

**Comment by twm** [comment]
Only a whole evening of re-running builds to get this green. :sob:

**Comment by rthille** [comment]
You could reduce the noise a lot by adding a retry on the produce test if it gets the 'not leader error', knowing that Kafka throws that error when it shouldn't.

**Comment by twm** [comment]
I was hesitant to do that without truly understanding what is going on, but if you say so, I will. Thanks!

**Comment by rthille** [comment]
Well, the produce test should be able to send messages as soon as the metadata says the topic is ready, but Kafka lies, so retrying on that one error, and possibly fetching the metadata in-between retries is a reasonable thing to do in the test to deal with the Kafka issue.  In real-life usage, the producer will retry those 'send-message' (or whatever that api is) calls anyway...

**Pull request merged**
