### PR TITLE
Travis with modern PyPy

### PR DESCRIPTION
**Pull request by twm**
I've yet to find where Travis documents these things. This is cargo-culted from https://github.com/html5lib/html5lib-python/pull/409.

### CODE REVIEW

**Comment by rthille** [comment]
Looks like 7.0 is out: http://doc.pypy.org/en/latest/release-v7.0.0.html

**Comment by twm** [comment]
Good points, I will try out PyPy 7.0 and add PyPy3. Thank you for the review!

**Comment by twm** [comment]
It looks like Travis doesn't have PyPy 7.0. :'( I'll roll that bit back.

**Comment by rthille** [comment]
> It looks like Travis doesn't have PyPy 7.0. :'( I'll roll that bit back.

Big Sad :-)

**Pull request merged**
