### PR TITLE
Fix map for side effects

### PR DESCRIPTION
**Pull request by twm**
map() can't be used for side effects in Python 3 as it is lazy.

- [x] Add missing test coverage

### CODE REVIEW

**Comment by rthille** [comment]
Expired Travis access token?

**Comment by twm** [comment]
Where did you see that, @rthille?

**Comment by rthille** [comment]
That's what I got when I clicked thru on the "Details" link to the right of "continuous-integration/travis-ci/pr — The Travis CI build failed"

**Comment by rthille** [comment]
From the current failure, it looks like the tear down of Producer might be racy:
```
AssertionError: Found 1 outstanding delayed calls:
<DelayedCall 0x7ff384233520 [0.225120067596s] called=0 cancelled=0 Deferred.callback([ProduceRequest(topic=u'test_throughput-SACkeUGuEP', partition=10, messages=[Message(magic=0, attributes=0, key=None,
```
That says to me that either the test didn't tear it down properly (wait for all the deferreds to be cancelled/complete) or Afkak itself doesn't properly shutdown the Producer in all cases.

**Comment by rthille** [comment]
Is there not coverage report generated by the builds anymore?

**Comment by twm** [comment]
Not by the Travis builds, no. I tried adding one here but it looks like it will be non-trivial so I will move those commits to a separate PR.

**Comment by twm** [comment]
I've kicked the builds a few times and am satisfied that the failures haven't been related to the changes here, so I will go ahead and merge.

**Pull request merged**
